plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.38'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "${mod_id}-forge-${minecraft_version}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        client {
            workingDirectory project.file('run')
            arg '--mixin.config=viewboard.mixins.json'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    testImplementation 'com.google.code.gson:gson:2.10.1'
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
    options.compilerArgs += ['-AdisableTargetValidator=true']
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'MixinConfigs': "${mod_id}.mixins.json"
        ])
    }
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
        mod_id         : mod_id,
        mod_name       : mod_name,
        mod_license    : mod_license,
        mod_version    : mod_version,
        mod_authors    : mod_authors,
        mod_description: mod_description,
        forge_version  : forge_version
    ]
    inputs.properties(replaceProperties)
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand(replaceProperties)
    }
}
