plugins {
    id 'java-library'
    id 'net.neoforged.moddev.legacyforge' version '2.0.141'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "${mod_id}-neoforge-${minecraft_version}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

legacyForge {
    enable {
        neoForgeVersion = neo_version
    }

    runs {
        client {
            client()
            programArgument '--mixin.config=viewboard.mixins.json'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
    options.compilerArgs += [
        "-AoutRefMapFile=${layout.buildDirectory.file("tmp/compileJava/${mod_id}.refmap.json").get().asFile}",
        "-AreobfTsrgFile=${layout.buildDirectory.file('moddev/artifacts/namedToIntermediate.tsrg').get().asFile}",
        '-AdefaultObfuscationEnv=searge',
        '-AmappingTypes=tsrg',
        '-AdisableTargetValidator=true'
    ]
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    testImplementation 'com.google.code.gson:gson:2.10.1'
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}

tasks.named('jar', Jar).configure {
    from(layout.buildDirectory.file("tmp/compileJava/${mod_id}.refmap.json")) {
        into ''
    }
    manifest {
        attributes([
            'MixinConfigs': "${mod_id}.mixins.json"
        ])
    }
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
        mod_id         : mod_id,
        mod_name       : mod_name,
        mod_license    : mod_license,
        mod_version    : mod_version,
        mod_authors    : mod_authors,
        mod_description: mod_description,
        neo_version    : neo_version
    ]
    inputs.properties(replaceProperties)
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand(replaceProperties)
    }
}
